### ISSUE TITLE
setCustomName method not working on 1.20.4

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/FastNBT#7]
Related to https://github.com/PluginBugs/Issues-LoneLibs/issues/2
```
Caused by: java.lang.NullPointerException: Cannot invoke "lonelibs.dev.lone.fastnbt.nms.nbt.IDataComponents.setCustomName(org.bukkit.inventory.ItemStack, String)" because "lonelibs.dev.lone.fastnbt.nms.nbt.NBT.dataComponents" is null
	at lonelibs.dev.lone.fastnbt.nms.nbt.NItem.setCustomName(NItem.java:182) ~[LoneLibs1.0.55.jar:?]
	at dev.lone.CinematicStudio.b.a(SourceFile:196) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at CinematicStudio.m.R.a(SourceFile:650) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at CinematicStudio.m.R.ai(SourceFile:256) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at CinematicStudio.m.R.b(SourceFile:98) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at CinematicStudio.m.al.a(SourceFile:311) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at CinematicStudio.m.ai.onCommand(SourceFile:37) ~[CinematicStudio_2.0.0-indev-9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
```

**Comment by narlideresolutions** [comment]
yav orospu çocukları sorunu çözsenize, Jun 26'da açılan issues hala çözülmemiş.

**Comment by LoneDev6** [comment]
Plugin is open source, you can fix it yourself "yav orospu çocukları" ;)

**Comment by narlideresolutions** [comment]
😃 😃 😃 😃 😃 😃 😃 😃 😃
